


-- Class:               CSE 3330
-- Semester:            Spring 2016
-- Student Name:        Lennix,Emmanuel,ejl4990
-- Student ID:          1001104990
-- Assignment:          project #1

SOURCE ejl4990_myDBdrop.sql;



CREATE TABLE PlaneType(

Maker		VARCHAR(15)	NOT NULL,
Model		VARCHAR(15)	NOT NULL,
FlyingSpeed	FLOAT(4),
GroundSpeed	FLOAT(4),

CONSTRAINT PT_PK
PRIMARY KEY(Maker,Model)

)ENGINE=InnoDB
;

CREATE TABLE Pilot( 
    
ID              INT(10)         NOT NULL,
Name            VARCHAR(20)     NOT NULL,
DateHired       DATE            NOT NULL,

CONSTRAINT PK_PILOT
PRIMARY KEY (ID)
    
)ENGINE=InnoDB
;



CREATE TABLE Airport(

Code            VARCHAR(3)      NOT NULL,
City            VARCHAR(15),    
State           VARCHAR(15),

CONSTRAINT PK_AIR
PRIMARY KEY (Code)

)ENGINE=InnoDB
;


CREATE TABLE Plane(

ID 		INT(10) 	NOT NULL,
Maker		VARCHAR(15) 	NOT NULL,
Model		VARCHAR(15)	NOT NULL,
LastMaint	VARCHAR(3),
LastMaintA	VARCHAR(3),	

CONSTRAINT P_PK
PRIMARY KEY (ID),

CONSTRAINT P_UN
UNIQUE(ID),

CONSTRAINT P_FK_MAKE_MODEL
FOREIGN	KEY (MAKER,Model) REFERENCES PlaneType(Maker,Model) ON UPDATE CASCADE,


FOREIGN KEY (LastMaintA)  REFERENCES Airport(Code) ON UPDATE CASCADE

)ENGINE=InnoDB
;

CREATE TABLE PlaneSeats(

Maker           VARCHAR(15)     NOT NULL,
Model           VARCHAR(15)     NOT NULL,
SeatType	VARCHAR(15)	NOT NULL,
NoOfSeats	VARCHAR(15),

CONSTRAINT PS_PK
PRIMARY KEY(Maker,Model,SeatType),

CONSTRAINT FK_PS
FOREIGN KEY (Maker,Model) REFERENCES PlaneType(Maker,Model) ON UPDATE CASCADE

)ENGINE=InnoDB
;


CREATE TABLE Flight(

FLNO		INT(4)		NOT NULL DEFAULT 0,
Meal		VARCHAR(15),
Smoking		CHAR,

CONSTRAINT PK_F
PRIMARY KEY(FLNO)


)ENGINE=InnoDB
;


CREATE TABLE FlightInstance(

FLNO		INT(4)		NOT NULL ,
FDate		DATE		NOT NULL,

CONSTRAINT PK_FI
PRIMARY KEY(FLNO,FDate),

CONSTRAINT FK_FI
FOREIGN KEY (FLNO) REFERENCES Flight(FLNO) ON UPDATE CASCADE

)ENGINE=InnoDB
;


CREATE TABLE FlightLeg(

FLNO		INT(4)		NOT NULL,
Seq		INT,
FromA		VARCHAR(3)	NOT NULL,
ToA		VARCHAR(3)	NOT NULL,
DeptTime	DATETIME,
ArrTime		DATETIME,
Plane		INT(10) 	NOT NULL,

CONSTRAINT PK_FL
PRIMARY KEY (FLNO,Seq),

CONSTRAINT FK_FL_FLNO
FOREIGN KEY (FLNO) REFERENCES Flight(FLNO) ON UPDATE CASCADE,

CONSTRAINT FK_FL_FA
FOREIGN KEY (FromA) REFERENCES Airport(Code) ON UPDATE CASCADE,

CONSTRAINT FK_FL_TA
FOREIGN KEY (ToA) REFERENCES Airport(Code) ON UPDATE CASCADE,

CONSTRAINT FK_FL_PLANE
FOREIGN KEY (Plane) REFERENCES Plane(ID) ON UPDATE CASCADE
)ENGINE=InnoDB
;



Create TABLE Passenger(

ID		INT(10)		NOT NULL,
Name		VARCHAR(20)	NOT NULL,
Phone		VARCHAR(13),

CONSTRAINT PK_PASS
PRIMARY KEY (ID)

)ENGINE=InnoDB
;


Create TABLE Reservation(

PassID		INT(10)		NOT NULL,
FLNO		INT(4)		NOT NULL,
FDate		DATE		NOT NULL,
FromA           VARCHAR(3)      NOT NULL,
ToA             VARCHAR(3)      NOT NULL,
SeatClass	CHAR,
DateBooked	DATE,
DateCancelled	DATE,


CONSTRAINT PK_RES
PRIMARY KEY (PassID,FLNO,FDate),

CONSTRAINT FK_RES_ID
FOREIGN KEY (PassID) REFERENCES Passenger(ID) ON UPDATE CASCADE,

CONSTRAINT FK_RES_FLNO_DATE
FOREIGN KEY (FLNO,FDate) REFERENCES FlightInstance(FLNO,FDate) ON UPDATE CASCADE,

CONSTRAINT FK_RES_FROM
FOREIGN KEY (FromA) REFERENCES Airport(Code) ON UPDATE CASCADE,

CONSTRAINT FK_RES_TO
FOREIGN KEY (ToA) REFERENCES Airport(Code) ON UPDATE CASCADE


)ENGINE=InnoDB
;


CREATE TABLE FlightLegInstance(

Seq             INT,
FLNO            INT(4)          NOT NULL,
FDate           DATE            NOT NULL,
ActDept         DATETIME,
ActArr          DATETIME,
Pilot           INT(10)		NOT NULL,

CONSTRAINT PK_FLI
PRIMARY KEY (Seq,FLNO,FDate),

FOREIGN KEY (FLNO,FDate) REFERENCES FlightInstance(FLNO,FDate) ON UPDATE CASCADE, 

FOREIGN KEY (Pilot) REFERENCES Pilot(ID) ON UPDATE CASCADE,

FOREIGN KEY (FLNO,Seq) REFERENCES FlightLeg(FLNO,Seq) ON UPDATE CASCADE


)ENGINE=InnoDB;

SHOW TABLES;
